In [49]:
import pandas as pd

df = pd.read_csv("../data/apple_dataset.csv")

In [50]:
df.head()

            Date  Close   High    Low   Open     Volume
0  13 April 2015  28.33  28.71  28.28  28.67  145460400
1  14 April 2015  28.21  28.43  28.12  28.36  102098400
2  15 April 2015  28.31  28.39  28.14  28.23  115881600
3  16 April 2015  28.18  28.38  28.16  28.20  113476000
4  17 April 2015  27.86  28.17  27.80  28.04  207828000

In [51]:
df.shape

(2517, 6)

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2517 non-null   str
 1   Close   2517 non-null   float64
 2   High    2517 non-null   float64
 3   Low     2517 non-null   float64
 4   Open    2517 non-null   float64
 5   Volume  2517 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 118.1 KB

In [53]:
df_clean = df.copy()

In [54]:
df_clean.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [55]:
df_clean.duplicated().sum()

np.int64(0)

In [56]:
df_clean["daily_range"] = (
    df_clean["High"]
    - df_clean["Low"]
)

In [57]:
df_clean["price_change"] = (
    df_clean["Close"] - 
    df_clean["Open"]
)

In [58]:
df_clean["daily_range"].describe()

count    2517.000000
mean        2.101625
std         2.063860
min         0.130000
25%         0.540000
50%         1.490000
75%         3.080000
max        28.720000
Name: daily_range, dtype: float64

In [59]:
df_clean["price_change"].describe()

count    2517.000000
mean        0.101196
std         1.808653
min       -14.280000
25%        -0.410000
50%         0.060000
75%         0.610000
max        26.900000
Name: price_change, dtype: float64

In [60]:
max_price_change = df_clean["price_change"].max()

In [61]:
min_price_change = df_clean["price_change"].min()

In [62]:
df_clean["price_change"] == max_price_change

0       False
1       False
2       False
3       False
4       False
        ...
2512    False
2513    False
2514     True
2515    False
2516    False
Name: price_change, Length: 2517, dtype: bool

In [63]:
df_clean["price_change"] == min_price_change

0       False
1       False
2       False
3       False
4       False
        ...
2512    False
2513     True
2514    False
2515    False
2516    False
Name: price_change, Length: 2517, dtype: bool

In [64]:
df_clean[df_clean["price_change"] == max_price_change]

,Date,Close,High,Low,Open,Volume,daily_range,price_change
2514,09 April 2025,198.85,200.61,171.89,171.95,184395900,28.72,26.9

In [65]:
df_clean[df_clean["price_change"] == min_price_change]

,Date,Close,High,Low,Open,Volume,daily_range,price_change
2513,08 April 2025,172.42,190.34,169.21,186.7,120859500,21.13,-14.28

In [66]:
df_clean["price_change"]==26.90

0       False
1       False
2       False
3       False
4       False
        ...
2512    False
2513    False
2514    False
2515    False
2516    False
Name: price_change, Length: 2517, dtype: bool

In [67]:
df_clean.to_csv(
    "../data/apple_clean.csv",
    index=False
)

In [68]:
df_clean["daily_return_pct"] = (
    (
        df_clean["Close"]
        - df_clean["Open"]
    )
    / df_clean["Open"]
) * 100

In [69]:
df_clean["daily_return_pct"].describe()

count    2517.000000
mean        0.094369
std         1.438613
min        -7.648634
25%        -0.643799
50%         0.097002
75%         0.868908
max        15.644083
Name: daily_return_pct, dtype: float64

In [70]:
df_clean.sort_values("price_change")

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
2513,08 April 2025,172.42,190.34,169.21,186.70,120859500,21.13,-14.28,-7.648634
2467,31 January 2025,235.74,246.92,233.18,246.92,101075100,13.74,-11.18,-4.527782
2457,16 January 2025,228.01,237.75,227.78,237.09,71759100,9.97,-9.08,-3.829769
2492,10 March 2025,227.48,236.16,224.22,235.54,72071200,11.94,-8.06,-3.421924
1780,05 May 2022,154.27,161.46,152.48,161.24,130525300,8.98,-6.97,-4.322749
...,...,...,...,...,...,...,...,...,...
1731,24 February 2022,160.15,160.25,149.58,150.15,141147500,10.67,10.00,6.660007
2344,05 August 2024,208.57,212.78,195.34,198.42,119548600,17.44,10.15,5.115412
2516,11 April 2025,198.15,199.54,186.06,186.10,87300000,13.48,12.05,6.475013
2307,11 June 2024,206.46,206.47,192.98,193.00,172373300,13.49,13.46,6.974093
2514,09 April 2025,198.85,200.61,171.89,171.95,184395900,28.72,26.90,15.644083

In [71]:
df_clean.sort_values(
    "price_change",
    ascending=False
)

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
2514,09 April 2025,198.85,200.61,171.89,171.95,184395900,28.72,26.90,15.644083
2307,11 June 2024,206.46,206.47,192.98,193.00,172373300,13.49,13.46,6.974093
2516,11 April 2025,198.15,199.54,186.06,186.10,87300000,13.48,12.05,6.475013
2344,05 August 2024,208.57,212.78,195.34,198.42,119548600,17.44,10.15,5.115412
1731,24 February 2022,160.15,160.25,149.58,150.15,141147500,10.67,10.00,6.660007
...,...,...,...,...,...,...,...,...,...
1780,05 May 2022,154.27,161.46,152.48,161.24,130525300,8.98,-6.97,-4.322749
2492,10 March 2025,227.48,236.16,224.22,235.54,72071200,11.94,-8.06,-3.421924
2457,16 January 2025,228.01,237.75,227.78,237.09,71759100,9.97,-9.08,-3.829769
2467,31 January 2025,235.74,246.92,233.18,246.92,101075100,13.74,-11.18,-4.527782
2513,08 April 2025,172.42,190.34,169.21,186.70,120859500,21.13,-14.28,-7.648634

In [72]:
df_clean.sort_values(
    "price_change",
    ascending=False,
)
df_clean["price_change"].head(5)

0   -0.34
1   -0.15
2    0.08
3   -0.02
4   -0.18
Name: price_change, dtype: float64

In [73]:
df_clean.sort_values(
    "price_change",
    ascending=True,
) .head(5)

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
2513,08 April 2025,172.42,190.34,169.21,186.70,120859500,21.13,-14.28,-7.648634
2467,31 January 2025,235.74,246.92,233.18,246.92,101075100,13.74,-11.18,-4.527782
2457,16 January 2025,228.01,237.75,227.78,237.09,71759100,9.97,-9.08,-3.829769
2492,10 March 2025,227.48,236.16,224.22,235.54,72071200,11.94,-8.06,-3.421924
1780,05 May 2022,154.27,161.46,152.48,161.24,130525300,8.98,-6.97,-4.322749

In [74]:
df_clean["daily_return_pct"] > 5

0       False
1       False
2       False
3       False
4       False
        ...
2512    False
2513    False
2514     True
2515    False
2516     True
Name: daily_return_pct, Length: 2517, dtype: bool

In [75]:
df_clean[
    df_clean["daily_return_pct"] > 5
]

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
93,24 August 2015,23.23,24.51,20.73,21.37,648825200,3.78,1.86,8.703790
711,06 February 2018,38.31,38.47,36.19,36.38,272975200,2.28,1.93,5.305113
934,26 December 2018,37.49,37.50,35.00,35.37,234330000,2.50,2.12,5.993780
1229,28 February 2020,66.34,67.56,62.22,62.43,426510000,5.34,3.91,6.263015
1230,02 March 2020,72.51,73.15,67.40,68.50,341397200,5.75,4.01,5.854015
1371,21 September 2020,107.34,107.45,100.53,101.94,195713800,6.92,5.40,5.297234
1731,24 February 2022,160.15,160.25,149.58,150.15,141147500,10.67,10.00,6.660007
1891,13 October 2022,141.11,141.70,132.61,133.22,113224000,9.09,7.89,5.922534
1902,28 October 2022,153.70,155.43,145.88,146.25,164762400,9.55,7.45,5.094017
2307,11 June 2024,206.46,206.47,192.98,193.00,172373300,13.49,13.46,6.974093
2344,05 August 2024,208.57,212.78,195.34,198.42,119548600,17.44,10.15,5.115412
2514,09 April 2025,198.85,200.61,171.89,171.95,184395900,28.72,26.90,15.644083
2516,11 April 2025,198.15,199.54,186.06,186.10,87300000,13.48,12.05,6.475013

In [76]:
big_gain_days = df_clean[
    df_clean["daily_return_pct"] > 5
]
#"The dataframe containing all days where returns exceeded 5%."

In [77]:
big_gain_days.head()
#inspect it

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
93,24 August 2015,23.23,24.51,20.73,21.37,648825200,3.78,1.86,8.703790
711,06 February 2018,38.31,38.47,36.19,36.38,272975200,2.28,1.93,5.305113
934,26 December 2018,37.49,37.50,35.00,35.37,234330000,2.50,2.12,5.993780
1229,28 February 2020,66.34,67.56,62.22,62.43,426510000,5.34,3.91,6.263015
1230,02 March 2020,72.51,73.15,67.40,68.50,341397200,5.75,4.01,5.854015

In [78]:
big_gain_days.info()

<class 'pandas.DataFrame'>
Index: 13 entries, 93 to 2516
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              13 non-null     str
 1   Close             13 non-null     float64
 2   High              13 non-null     float64
 3   Low               13 non-null     float64
 4   Open              13 non-null     float64
 5   Volume            13 non-null     int64
 6   daily_range       13 non-null     float64
 7   price_change      13 non-null     float64
 8   daily_return_pct  13 non-null     float64
dtypes: float64(7), int64(1), str(1)
memory usage: 1.0 KB

In [79]:
big_gain_days.shape

(13, 9)

In [80]:
# sort the big_gain_days dataframe by daily_return_pct in descending order
df_clean
big_gain_days_sorted = big_gain_days.sort_values(
    "daily_return_pct",
    ascending=False
)
big_gain_days_sorted.head(5)

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
2514,09 April 2025,198.85,200.61,171.89,171.95,184395900,28.72,26.90,15.644083
93,24 August 2015,23.23,24.51,20.73,21.37,648825200,3.78,1.86,8.703790
2307,11 June 2024,206.46,206.47,192.98,193.00,172373300,13.49,13.46,6.974093
1731,24 February 2022,160.15,160.25,149.58,150.15,141147500,10.67,10.00,6.660007
2516,11 April 2025,198.15,199.54,186.06,186.10,87300000,13.48,12.05,6.475013

In [81]:
# Manager: "Show me 10 largest daily returns greater than 3%"
from tracemalloc import Filter


big_gain_days = df_clean[
    df_clean["daily_return_pct"] > 3
]

big_gain_days_sorted = big_gain_days.sort_values(
    "daily_return_pct",
    ascending=False
)

big_gain_days_sorted.head(10)

# Let's read this like an engineer:
    # Filter the dataframe to only include days where the daily return was greater than 3%.
    # Sort those days from highest return to lowest.
    # Display the first 10 rows (the 10 biggest gains above 3%).

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
2514,09 April 2025,198.85,200.61,171.89,171.95,184395900,28.72,26.90,15.644083
93,24 August 2015,23.23,24.51,20.73,21.37,648825200,3.78,1.86,8.703790
2307,11 June 2024,206.46,206.47,192.98,193.00,172373300,13.49,13.46,6.974093
1731,24 February 2022,160.15,160.25,149.58,150.15,141147500,10.67,10.00,6.660007
2516,11 April 2025,198.15,199.54,186.06,186.10,87300000,13.48,12.05,6.475013
1229,28 February 2020,66.34,67.56,62.22,62.43,426510000,5.34,3.91,6.263015
934,26 December 2018,37.49,37.50,35.00,35.37,234330000,2.50,2.12,5.993780
1891,13 October 2022,141.11,141.70,132.61,133.22,113224000,9.09,7.89,5.922534
1230,02 March 2020,72.51,73.15,67.40,68.50,341397200,5.75,4.01,5.854015
711,06 February 2018,38.31,38.47,36.19,36.38,272975200,2.28,1.93,5.305113

In [82]:
# Step 1: filter rows where daily return > 3%
filtered = df_clean[df_clean["daily_return_pct"] > 3]

# Step 2: select only the columns we care about
selected_cols = filtered[["Date", "Close", "daily_return_pct"]]

# Step 3: sort by daily return (biggest gains first)
sorted_data = selected_cols.sort_values(
    "daily_return_pct",
    ascending=False
)

# Step 4: show top 10 results
sorted_data.head(10)

                  Date   Close  daily_return_pct
2514     09 April 2025  198.85         15.644083
93      24 August 2015   23.23          8.703790
2307      11 June 2024  206.46          6.974093
1731  24 February 2022  160.15          6.660007
2516     11 April 2025  198.15          6.475013
1229  28 February 2020   66.34          6.263015
934   26 December 2018   37.49          5.993780
1891   13 October 2022  141.11          5.922534
1230     02 March 2020   72.51          5.854015
711   06 February 2018   38.31          5.305113

In [83]:
# even more professional engineer (compressed) version:

df_clean[
    df_clean["daily_return_pct"] > 3
][["Date", "Close", "daily_return_pct"]].sort_values(
    "daily_return_pct",
    ascending=False
).head(10)

                  Date   Close  daily_return_pct
2514     09 April 2025  198.85         15.644083
93      24 August 2015   23.23          8.703790
2307      11 June 2024  206.46          6.974093
1731  24 February 2022  160.15          6.660007
2516     11 April 2025  198.15          6.475013
1229  28 February 2020   66.34          6.263015
934   26 December 2018   37.49          5.993780
1891   13 October 2022  141.11          5.922534
1230     02 March 2020   72.51          5.854015
711   06 February 2018   38.31          5.305113

In [84]:
# step 1 - filtering the rows:
biggest_losses = df_clean[df_clean["daily_return_pct"] < -3]


# step 2 - selecting the cols:
selected_cols=biggest_losses[["Date", "Open", "Close", "daily_return_pct"]]


# step 3 - sorting by daily_return_pct:

sorted_data = selected_cols.sort_values(

"daily_return_pct",

ascending = True

)


# step 4 - showing top 10 biggest losses
sorted_data.head(10)

                   Date    Open   Close  daily_return_pct
2513      08 April 2025  186.70  172.42         -7.648634
1244      20 March 2020   59.99   55.63         -7.267878
94       25 August 2015   25.03   23.37         -6.632042
1364  10 September 2020  117.36  110.66         -5.708930
1360  03 September 2020  123.75  117.87         -4.751515
1231      03 March 2020   73.69   70.21         -4.722486
1784        11 May 2022  151.27  144.38         -4.554770
2467    31 January 2025  246.92  235.74         -4.527782
1359  02 September 2020  134.16  128.13         -4.494633
1780        05 May 2022  161.24  154.27         -4.322749

In [85]:
biggest_losses.shape

(56, 9)

In [86]:
df_clean["Date"].head()

0    13 April 2015
1    14 April 2015
2    15 April 2015
3    16 April 2015
4    17 April 2015
Name: Date, dtype: str

In [87]:
df_clean["Date"] = pd.to_datetime(df_clean["Date"])

In [88]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              2517 non-null   datetime64[us]
 1   Close             2517 non-null   float64
 2   High              2517 non-null   float64
 3   Low               2517 non-null   float64
 4   Open              2517 non-null   float64
 5   Volume            2517 non-null   int64
 6   daily_range       2517 non-null   float64
 7   price_change      2517 non-null   float64
 8   daily_return_pct  2517 non-null   float64
dtypes: datetime64[us](1), float64(7), int64(1)
memory usage: 177.1 KB

In [89]:
df_clean["Year"] = df_clean["Date"].dt.year

In [90]:
df_clean[["Date", "Year"]].head()

        Date  Year
0 2015-04-13  2015
1 2015-04-14  2015
2 2015-04-15  2015
3 2015-04-16  2015
4 2015-04-17  2015

In [91]:
df_clean["Year"].describe()

count    2517.000000
mean     2019.770362
std         2.908055
min      2015.000000
25%      2017.000000
50%      2020.000000
75%      2022.000000
max      2025.000000
Name: Year, dtype: float64

In [92]:
df_clean.groupby("Year")["Date"].count()

Year
2015    184
2016    252
2017    251
2018    251
2019    252
2020    253
2021    252
2022    251
2023    250
2024    252
2025     69
Name: Date, dtype: int64

In [93]:
df_clean.groupby("Year")["daily_return_pct"].mean()

Year
2015   -0.087168
2016    0.094433
2017    0.084779
2018   -0.025900
2019    0.186814
2020    0.154065
2021    0.087772
2022    0.039212
2023    0.189704
2024    0.120333
2025    0.278596
Name: daily_return_pct, dtype: float64

In [94]:
df_clean.groupby("Year").mean()

,Date,Close,High,Low,Open,Volume,daily_range,price_change,daily_return_pct
Year,,,,,,,,,
2015,2015-08-21 06:23:28.695652,26.891141,27.160924,26.631196,26.918913,2.006644e+08,0.529728,-0.027772,-0.087168
2016,2016-07-02 16:51:25.714285,23.959524,24.147460,23.750437,23.937302,1.536901e+08,0.397024,0.022222,0.094433
2017,2017-07-02 07:21:45.179282,35.134104,35.333227,34.885737,35.109323,1.085383e+08,0.447490,0.024781,0.084779
2018,2018-07-01 10:59:45.657370,44.791434,45.251275,44.348048,44.805259,1.360803e+08,0.903227,-0.013825,-0.025900
2019,2019-07-02 09:02:51.428571,50.119683,50.498651,49.641984,50.026667,1.121228e+08,0.856667,0.093016,0.186814
2020,2020-07-02 12:42:41.264822,92.837194,94.117194,91.440711,92.760040,1.575646e+08,2.676482,0.077154,0.154065
2021,2021-07-03 16:28:34.285714,138.194365,139.525040,136.708532,138.068968,9.052463e+07,2.816508,0.125397,0.087772
2022,2022-07-02 15:23:39.920318,152.607888,154.650159,150.494781,152.575896,8.791038e+07,4.155378,0.031992,0.039212
2023,2023-07-02 09:18:43.200000,171.094320,172.390920,169.540520,170.804240,5.921703e+07,2.850400,0.290080,0.189704
2024,2024-07-01 19:37:08.571428,206.542659,208.241587,204.559762,206.290079,5.712725e+07,3.681825,0.252579,0.120333
2025,2025-02-22 05:33:54.782608,227.156087,230.386522,223.617971,226.682029,6.020802e+07,6.768551,0.474058,0.278596

In [95]:
df_clean.groupby("Year")["Date"].mean()

Year
2015   2015-08-21 06:23:28.695652
2016   2016-07-02 16:51:25.714285
2017   2017-07-02 07:21:45.179282
2018   2018-07-01 10:59:45.657370
2019   2019-07-02 09:02:51.428571
2020   2020-07-02 12:42:41.264822
2021   2021-07-03 16:28:34.285714
2022   2022-07-02 15:23:39.920318
2023   2023-07-02 09:18:43.200000
2024   2024-07-01 19:37:08.571428
2025   2025-02-22 05:33:54.782608
Name: Date, dtype: datetime64[us]

In [96]:
# step 1 group by year - Put rows from the same year together.
# step 2 - aggregate daily return pct by year using mean - Calculate the average daily return for each year.

yearly_returns = df_clean.groupby("Year")["daily_return_pct"].mean()

# step 3 - sort the results by daily return pct in descending order - Show the best years first.
# Sorting helps us identify rankings and priorities.
yearly_returns.sort_values(
    ascending=False
    ).head(10)

# Repeated workflow: Raw Data -> Group -> Aggregate -> Sort -> Report

Year
2025    0.278596
2023    0.189704
2019    0.186814
2020    0.154065
2024    0.120333
2016    0.094433
2021    0.087772
2017    0.084779
2022    0.039212
2018   -0.025900
Name: daily_return_pct, dtype: float64

In [97]:
yearly_returns.sort_values(
    ascending=False
)

Year
2025    0.278596
2023    0.189704
2019    0.186814
2020    0.154065
2024    0.120333
2016    0.094433
2021    0.087772
2017    0.084779
2022    0.039212
2018   -0.025900
2015   -0.087168
Name: daily_return_pct, dtype: float64

In [98]:
yearly_returns.sort_values(
    ascending=False
).head(3)

Year
2025    0.278596
2023    0.189704
2019    0.186814
Name: daily_return_pct, dtype: float64